### ISSUE TITLE
Move off of Docker Hub's builder infrastructure to GitHub Actions.

### ISSUE THREAD

**Issue by Ferroin** [netdata/helper-images#58]
Docker Hub's automated builder infrastructure has horrendous queue times and is not exactly user friendly to work with.  The queue times have caused numerous unnecessary delays  on multiple occasions.

Given this, we should move our actual build and publishing logic to GitHub Actions, as we already know that works and has good performance.

**Comment by prologic** [comment]
It's actually fairly trivial to do this.

I assume we want to also just publish the images from our GHA workflows too right?

**Comment by Ferroin** [comment]
> It's actually fairly trivial to do this.

Agreed, I just hadn't got around to it yet.

> I assume we want to also just publish the images from our GHA workflows too right?

Essentially yes.

As mentioned in the description, Docker Hub is way too slow and inconsistent in terms of timing for us to rely on for things we need to change with any regularity. This is part of why we're avoiding it for our public Docker images for Netdata itself, queuing a build doesn't even guarantee that the build gets run the same _day_, let alone in a reasonable amount of time on that day.

**Comment by prologic** [comment]
Adding to our Backlog but this is low-pri until we finish more important work or we have an insurge of "helper-images" updates that take forever to finish and we just fix it then.
